import { PrismaClient, AtsType } from '@prisma/client'

const prisma = new PrismaClient()

const JOBS = [
  // Greenhouse jobs
  {
    company: 'Linear',
    role: 'Senior Software Engineer',
    description: 'Build the issue tracking tool that engineers actually love. Work on high-performance React with real-time sync and a beautiful desktop-class UI.',
    applyUrl: 'https://boards.greenhouse.io/linear/jobs/4567890',
    atsType: AtsType.GREENHOUSE,
    location: 'Remote (US)',
    salaryMin: 180000,
    salaryMax: 240000,
    tags: ['Series B', 'Remote', 'React', 'TypeScript'],
    logoUrl: null,
  },
  {
    company: 'Vercel',
    role: 'Staff Engineer – Edge Runtime',
    description: 'Own the runtime layer that powers millions of deployments. Work across V8 isolates, edge workers, and the Next.js framework itself.',
    applyUrl: 'https://boards.greenhouse.io/vercel/jobs/5678901',
    atsType: AtsType.GREENHOUSE,
    location: 'Remote',
    salaryMin: 200000,
    salaryMax: 280000,
    tags: ['Series C', 'Remote', 'Infra', 'Edge'],
    logoUrl: null,
  },
  {
    company: 'Retool',
    role: 'Product Engineer',
    description: 'Build the primitives that let companies build internal tools 10x faster. You\'ll work across the full stack with a very high bar for quality.',
    applyUrl: 'https://boards.greenhouse.io/retool/jobs/6789012',
    atsType: AtsType.GREENHOUSE,
    location: 'San Francisco, CA',
    salaryMin: 165000,
    salaryMax: 220000,
    tags: ['Series C', 'Hybrid', 'Full-Stack', 'No-Code'],
    logoUrl: null,
  },
  {
    company: 'Loom',
    role: 'iOS Engineer',
    description: 'Own the iOS recording and playback experience for Loom\'s 20M+ users. Ship features that feel magical on the best mobile hardware available.',
    applyUrl: 'https://boards.greenhouse.io/loom/jobs/7890123',
    atsType: AtsType.GREENHOUSE,
    location: 'San Francisco, CA',
    salaryMin: 155000,
    salaryMax: 210000,
    tags: ['Acquired', 'Hybrid', 'iOS', 'Swift'],
    logoUrl: null,
  },
  {
    company: 'Notion',
    role: 'Backend Engineer – Search',
    description: 'Scale search across billions of blocks. Own relevance tuning, indexing pipelines, and query performance for one of the fastest-growing productivity tools.',
    applyUrl: 'https://boards.greenhouse.io/notion/jobs/8901234',
    atsType: AtsType.GREENHOUSE,
    location: 'New York, NY',
    salaryMin: 170000,
    salaryMax: 235000,
    tags: ['Series C', 'Hybrid', 'Backend', 'Search'],
    logoUrl: null,
  },
  {
    company: 'Figma',
    role: 'Infrastructure Engineer',
    description: 'Operate Figma\'s multi-region infrastructure at massive scale. Work on Kubernetes, observability, and the deployment pipelines powering 4M+ designs.',
    applyUrl: 'https://boards.greenhouse.io/figma/jobs/9012345',
    atsType: AtsType.GREENHOUSE,
    location: 'San Francisco, CA',
    salaryMin: 190000,
    salaryMax: 260000,
    tags: ['Pre-IPO', 'Hybrid', 'Infra', 'Kubernetes'],
    logoUrl: null,
  },
  {
    company: 'Brex',
    role: 'Senior Fullstack Engineer',
    description: 'Build the financial operating system for startups. Work on expense management, card issuance, and spend intelligence with millions in daily transaction volume.',
    applyUrl: 'https://boards.greenhouse.io/brex/jobs/1234561',
    atsType: AtsType.GREENHOUSE,
    location: 'Remote (US)',
    salaryMin: 175000,
    salaryMax: 240000,
    tags: ['Series D', 'Remote', 'Fintech', 'Full-Stack'],
    logoUrl: null,
  },
  {
    company: 'Rippling',
    role: 'Software Engineer – Platform',
    description: 'Own the compound app platform that lets Rippling ship 20+ products from one codebase. Build the abstractions other engineers build on top of.',
    applyUrl: 'https://boards.greenhouse.io/rippling/jobs/2345672',
    atsType: AtsType.GREENHOUSE,
    location: 'San Francisco, CA',
    salaryMin: 160000,
    salaryMax: 220000,
    tags: ['Series F', 'Hybrid', 'Platform', 'HRTech'],
    logoUrl: null,
  },
  // Lever jobs
  {
    company: 'Cursor',
    role: 'AI Research Engineer',
    description: 'Push the frontier of AI-powered code editing. Work directly on the model layer, context management, and the novel UX patterns that define the editor.',
    applyUrl: 'https://jobs.lever.co/cursor/ab12cd34-ef56-7890-abcd-ef1234567890',
    atsType: AtsType.LEVER,
    location: 'San Francisco, CA',
    salaryMin: 200000,
    salaryMax: 300000,
    tags: ['Series A', 'Onsite', 'AI/ML', 'Developer Tools'],
    logoUrl: null,
  },
  {
    company: 'Perplexity',
    role: 'Software Engineer – Infra',
    description: 'Scale the infrastructure powering hundreds of millions of AI search queries. Own reliability, cost optimization, and the GPU orchestration layer.',
    applyUrl: 'https://jobs.lever.co/perplexity/bc23de45-fg67-8901-bcde-fg2345678901',
    atsType: AtsType.LEVER,
    location: 'San Francisco, CA',
    salaryMin: 185000,
    salaryMax: 260000,
    tags: ['Series B', 'Hybrid', 'AI', 'Infra'],
    logoUrl: null,
  },
  {
    company: 'Anyscale',
    role: 'Developer Advocate',
    description: 'Help the ML engineering community build distributed applications on Ray. Create content, demos, and guides that make complex distributed systems approachable.',
    applyUrl: 'https://jobs.lever.co/anyscale/cd34ef56-gh78-9012-cdef-gh3456789012',
    atsType: AtsType.LEVER,
    location: 'Remote',
    salaryMin: 130000,
    salaryMax: 180000,
    tags: ['Series C', 'Remote', 'DevRel', 'ML'],
    logoUrl: null,
  },
  {
    company: 'Hex',
    role: 'Frontend Engineer',
    description: 'Build the collaborative notebook experience that\'s replacing dashboards for data teams. Own editor performance, real-time sync, and beautiful data viz components.',
    applyUrl: 'https://jobs.lever.co/hex/de45fg67-hi89-0123-defg-hi4567890123',
    atsType: AtsType.LEVER,
    location: 'Remote (US)',
    salaryMin: 160000,
    salaryMax: 215000,
    tags: ['Series B', 'Remote', 'Data', 'Frontend'],
    logoUrl: null,
  },
  {
    company: 'Replit',
    role: 'Full-Stack Engineer',
    description: 'Build the collaborative browser IDE used by 20M+ developers. Work on the code execution layer, AI integrations, and the hosting infrastructure.',
    applyUrl: 'https://jobs.lever.co/replit/ef56gh78-ij90-1234-efgh-ij5678901234',
    atsType: AtsType.LEVER,
    location: 'Remote',
    salaryMin: 150000,
    salaryMax: 210000,
    tags: ['Series B', 'Remote', 'IDE', 'AI'],
    logoUrl: null,
  },
  {
    company: 'Modal',
    role: 'Infrastructure Engineer',
    description: 'Build the serverless GPU cloud from scratch. Own the container orchestration, network layer, and the developer experience that makes Modal feel like magic.',
    applyUrl: 'https://jobs.lever.co/modal/fg67hi89-jk01-2345-fghi-jk6789012345',
    atsType: AtsType.LEVER,
    location: 'New York, NY',
    salaryMin: 180000,
    salaryMax: 250000,
    tags: ['Series A', 'Hybrid', 'Cloud', 'GPUs'],
    logoUrl: null,
  },
  {
    company: 'Runway',
    role: 'Machine Learning Engineer',
    description: 'Build the generative video models powering the next era of creative tools. Work on diffusion models, video understanding, and real-time inference.',
    applyUrl: 'https://jobs.lever.co/runway/gh78ij90-kl12-3456-ghij-kl7890123456',
    atsType: AtsType.LEVER,
    location: 'New York, NY',
    salaryMin: 175000,
    salaryMax: 250000,
    tags: ['Series C', 'Hybrid', 'Generative AI', 'Video'],
    logoUrl: null,
  },
  {
    company: 'Supabase',
    role: 'Developer Experience Engineer',
    description: 'Own the SDK, CLI, and docs experience for Supabase\'s growing developer community. Reduce friction from sign-up to production for hundreds of thousands of developers.',
    applyUrl: 'https://jobs.lever.co/supabase/hi89jk01-lm23-4567-hijk-lm8901234567',
    atsType: AtsType.LEVER,
    location: 'Remote',
    salaryMin: 140000,
    salaryMax: 195000,
    tags: ['Series C', 'Remote', 'DevEx', 'Open Source'],
    logoUrl: null,
  },
  // Workday jobs
  {
    company: 'Stripe',
    role: 'Software Engineer, Payments',
    description: 'Own the payment processing infrastructure that moves trillions of dollars annually. Work on latency, reliability, and the new payment methods shaping commerce.',
    applyUrl: 'https://stripe.wd5.myworkday.com/stripe/d/job/1234',
    atsType: AtsType.WORKDAY,
    location: 'San Francisco, CA',
    salaryMin: 185000,
    salaryMax: 270000,
    tags: ['Pre-IPO', 'Hybrid', 'Payments', 'Infra'],
    logoUrl: null,
  },
  {
    company: 'Airbnb',
    role: 'Senior Frontend Engineer',
    description: 'Build the booking flow, search experience, and host tools used by millions of travelers and hosts worldwide. Work on the design system that scales to every market.',
    applyUrl: 'https://airbnb.wd5.myworkday.com/airbnb/d/job/5678',
    atsType: AtsType.WORKDAY,
    location: 'San Francisco, CA',
    salaryMin: 200000,
    salaryMax: 265000,
    tags: ['Public', 'Hybrid', 'Frontend', 'Design Systems'],
    logoUrl: null,
  },
  {
    company: 'Lyft',
    role: 'Data Engineer',
    description: 'Build the data infrastructure powering Lyft\'s marketplace. Own the streaming pipelines, data quality frameworks, and the analytics systems used to price rides.',
    applyUrl: 'https://lyft.wd1.myworkday.com/lyft/d/job/9012',
    atsType: AtsType.WORKDAY,
    location: 'Seattle, WA',
    salaryMin: 165000,
    salaryMax: 225000,
    tags: ['Public', 'Hybrid', 'Data', 'Streaming'],
    logoUrl: null,
  },
  {
    company: 'Pinterest',
    role: 'ML Engineer – Recommendations',
    description: 'Build the recommendation systems surfacing content for 450M+ monthly users. Own model training, feature engineering, and the serving infrastructure at Pinterest scale.',
    applyUrl: 'https://pinterest.wd5.myworkday.com/pinterest/d/job/3456',
    atsType: AtsType.WORKDAY,
    location: 'San Francisco, CA',
    salaryMin: 180000,
    salaryMax: 250000,
    tags: ['Public', 'Hybrid', 'ML', 'Recommendations'],
    logoUrl: null,
  },
  // Custom ATS jobs
  {
    company: 'Anthropic',
    role: 'Software Engineer – Claude.ai',
    description: 'Build the web product that brings Claude to millions of users. Own the conversation UI, streaming infrastructure, and the features that make Claude the most useful AI assistant.',
    applyUrl: 'https://anthropic.com/careers/4567890',
    atsType: AtsType.CUSTOM,
    location: 'San Francisco, CA',
    salaryMin: 200000,
    salaryMax: 320000,
    tags: ['Series E', 'Hybrid', 'AI Safety', 'Product'],
    logoUrl: null,
  },
  {
    company: 'OpenAI',
    role: 'Frontend Engineer',
    description: 'Build ChatGPT and the OpenAI developer platform. Own the real-time streaming UI, plugin integrations, and the web interfaces that 100M+ users interact with daily.',
    applyUrl: 'https://openai.com/careers/frontend-engineer',
    atsType: AtsType.CUSTOM,
    location: 'San Francisco, CA',
    salaryMin: 200000,
    salaryMax: 350000,
    tags: ['Series ?', 'Hybrid', 'AI', 'ChatGPT'],
    logoUrl: null,
  },
  {
    company: 'Mistral AI',
    role: 'Software Engineer – API Platform',
    description: 'Build the API infrastructure for Mistral\'s model serving. Work on low-latency inference, rate limiting, billing integrations, and the developer dashboard.',
    applyUrl: 'https://mistral.ai/company/careers/api-platform',
    atsType: AtsType.CUSTOM,
    location: 'Paris, France (Remote OK)',
    salaryMin: 120000,
    salaryMax: 180000,
    tags: ['Series B', 'Remote-Friendly', 'AI', 'API'],
    logoUrl: null,
  },
  {
    company: 'Together AI',
    role: 'Infrastructure Engineer',
    description: 'Scale the GPU cloud that powers fine-tuning and inference for thousands of AI applications. Own cluster management, networking, and the cloud-hypervisor layer.',
    applyUrl: 'https://together.ai/careers/infra-engineer',
    atsType: AtsType.CUSTOM,
    location: 'San Francisco, CA',
    salaryMin: 175000,
    salaryMax: 250000,
    tags: ['Series A', 'Hybrid', 'AI Infra', 'GPUs'],
    logoUrl: null,
  },
  {
    company: 'Groq',
    role: 'Compiler Engineer',
    description: 'Build the compiler that maps ML models to LPU silicon. Own graph optimization, kernel scheduling, and the toolchain that makes Groq the fastest inference chip available.',
    applyUrl: 'https://groq.com/careers/compiler-engineer',
    atsType: AtsType.CUSTOM,
    location: 'Mountain View, CA',
    salaryMin: 200000,
    salaryMax: 290000,
    tags: ['Series D', 'Onsite', 'Hardware', 'Compilers'],
    logoUrl: null,
  },
  {
    company: 'Weights & Biases',
    role: 'Product Engineer',
    description: 'Build the ML experiment tracking platform used by teams at OpenAI, NVIDIA, and thousands of research labs. Own the training run visualization and model registry.',
    applyUrl: 'https://wandb.ai/site/careers/product-engineer',
    atsType: AtsType.CUSTOM,
    location: 'Remote',
    salaryMin: 155000,
    salaryMax: 220000,
    tags: ['Series C', 'Remote', 'MLOps', 'Developer Tools'],
    logoUrl: null,
  },
  {
    company: 'Cohere',
    role: 'Applied ML Engineer',
    description: 'Build retrieval-augmented generation and enterprise search products on top of Cohere\'s language models. Own the RAG pipeline, embedding infrastructure, and customer integrations.',
    applyUrl: 'https://cohere.com/careers/applied-ml-engineer',
    atsType: AtsType.CUSTOM,
    location: 'Toronto, ON (Remote OK)',
    salaryMin: 150000,
    salaryMax: 220000,
    tags: ['Series C', 'Remote-Friendly', 'NLP', 'Enterprise'],
    logoUrl: null,
  },
  {
    company: 'Scale AI',
    role: 'Software Engineer – Data Pipeline',
    description: 'Build the data pipelines that power AI training datasets for the world\'s leading model labs. Own ingestion, quality checks, annotation tooling, and data delivery.',
    applyUrl: 'https://scale.com/careers/data-pipeline-engineer',
    atsType: AtsType.CUSTOM,
    location: 'San Francisco, CA',
    salaryMin: 165000,
    salaryMax: 230000,
    tags: ['Series F', 'Hybrid', 'Data', 'AI'],
    logoUrl: null,
  },
  {
    company: 'Character.AI',
    role: 'Backend Engineer – Inference',
    description: 'Own the inference serving layer for Character.AI\'s conversational models at massive scale. Build the systems handling billions of messages per day.',
    applyUrl: 'https://character.ai/careers/backend-inference',
    atsType: AtsType.CUSTOM,
    location: 'Menlo Park, CA',
    salaryMin: 180000,
    salaryMax: 260000,
    tags: ['Series B', 'Hybrid', 'LLM', 'Inference'],
    logoUrl: null,
  },
  {
    company: 'Hugging Face',
    role: 'ML Engineer – Hub',
    description: 'Build the infrastructure for the world\'s largest open-source ML model hub. Own dataset versioning, model card pipelines, and the Spaces deployment platform.',
    applyUrl: 'https://apply.workable.com/huggingface/j/AB12CD34EF',
    atsType: AtsType.CUSTOM,
    location: 'Remote',
    salaryMin: 140000,
    salaryMax: 200000,
    tags: ['Series D', 'Remote', 'Open Source', 'ML'],
    logoUrl: null,
  },
  {
    company: 'Imbue',
    role: 'Software Engineer – Training',
    description: 'Build the training infrastructure for agents that can reason and code. Work on large-scale distributed training, experiment orchestration, and evaluation frameworks.',
    applyUrl: 'https://imbue.com/careers/training-engineer',
    atsType: AtsType.CUSTOM,
    location: 'San Francisco, CA',
    salaryMin: 190000,
    salaryMax: 280000,
    tags: ['Series B', 'Onsite', 'Agents', 'Training'],
    logoUrl: null,
  },
  // More Greenhouse
  {
    company: 'Arc',
    role: 'Software Engineer',
    description: 'Build the browser that thinks differently about tabs, spaces, and the way people actually work on the web. Work on the Chromium layer, Swift UI, and novel navigation paradigms.',
    applyUrl: 'https://boards.greenhouse.io/arcbrowser/jobs/3456781',
    atsType: AtsType.GREENHOUSE,
    location: 'New York, NY',
    salaryMin: 160000,
    salaryMax: 225000,
    tags: ['Series C', 'Hybrid', 'Browser', 'Swift'],
    logoUrl: null,
  },
  {
    company: 'Ramp',
    role: 'Backend Engineer – Accounting',
    description: 'Build the accounting automation engine that closes books in hours instead of weeks. Own the GL sync, transaction categorization, and the rule engine powering Ramp Intelligence.',
    applyUrl: 'https://boards.greenhouse.io/ramp/jobs/4567892',
    atsType: AtsType.GREENHOUSE,
    location: 'New York, NY',
    salaryMin: 170000,
    salaryMax: 235000,
    tags: ['Series D', 'Hybrid', 'Fintech', 'Accounting'],
    logoUrl: null,
  },
  {
    company: 'Liveblocks',
    role: 'Developer Relations Engineer',
    description: 'Help developers build collaborative features with Liveblocks APIs. Create demos, write technical content, and be the voice of the community inside the product team.',
    applyUrl: 'https://boards.greenhouse.io/liveblocks/jobs/5678903',
    atsType: AtsType.GREENHOUSE,
    location: 'Remote',
    salaryMin: 120000,
    salaryMax: 170000,
    tags: ['Seed', 'Remote', 'DevRel', 'Real-Time'],
    logoUrl: null,
  },
  // More Lever
  {
    company: 'Turso',
    role: 'Distributed Systems Engineer',
    description: 'Build the globally distributed SQLite database. Work on the replication layer, edge node placement, and the Rust runtime powering Turso\'s sub-millisecond queries.',
    applyUrl: 'https://jobs.lever.co/turso/ij90kl12-mn34-5678-ijkl-mn9012345678',
    atsType: AtsType.LEVER,
    location: 'Remote',
    salaryMin: 160000,
    salaryMax: 230000,
    tags: ['Seed', 'Remote', 'Databases', 'Rust'],
    logoUrl: null,
  },
  {
    company: 'Temporal',
    role: 'Software Engineer – Cloud',
    description: 'Build the managed service for Temporal\'s open-source workflow engine. Own the multi-tenant control plane, namespace isolation, and the customer onboarding infrastructure.',
    applyUrl: 'https://jobs.lever.co/temporal/jk01lm23-no45-6789-jklm-no0123456789',
    atsType: AtsType.LEVER,
    location: 'Remote (US)',
    salaryMin: 170000,
    salaryMax: 240000,
    tags: ['Series B', 'Remote', 'Workflows', 'Cloud'],
    logoUrl: null,
  },
  {
    company: 'Neon',
    role: 'Database Engineer',
    description: 'Work on Neon\'s serverless Postgres infrastructure. Own the storage disaggregation layer, branching semantics, and the autoscaling engine that makes Neon feel instant.',
    applyUrl: 'https://jobs.lever.co/neon/kl12mn34-op56-7890-klmn-op1234567890',
    atsType: AtsType.LEVER,
    location: 'Remote',
    salaryMin: 165000,
    salaryMax: 230000,
    tags: ['Series B', 'Remote', 'Postgres', 'Serverless'],
    logoUrl: null,
  },
]

async function main() {
  console.log('Seeding database...')

  // Upsert default user
  const user = await prisma.user.upsert({
    where: { email: 'demo@chiaro.app' },
    update: {},
    create: {
      name: 'Demo User',
      email: 'demo@chiaro.app',
      phone: '+1 (415) 555-0100',
      linkedinUrl: 'https://linkedin.com/in/demo-user',
      githubUrl: 'https://github.com/demo-user',
      location: 'San Francisco, CA',
    },
  })
  console.log(`Created user: ${user.email}`)

  // Delete existing jobs and recreate
  await prisma.application.deleteMany()
  await prisma.job.deleteMany()

  for (const job of JOBS) {
    await prisma.job.create({ data: job })
  }

  console.log(`Seeded ${JOBS.length} jobs`)
  console.log('Done!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
